CREATE TABLE [dbo].[Pet]
(
	[PetName] NVARCHAR(15) NOT NULL,
	[OwnerID] NVARCHAR(4) NOT NULL,
	[PetType] NVARCHAR(15) NOT NULL
	CONSTRAINT PK_PET PRIMARY KEY (PetName, OwnerID)
	CONSTRAINT FK_OWNER_PET FOREIGN KEY (OwnerID) REFERENCES [Owner](OwnerID)
)
